### PR TITLE
fix(cms-api): add .js extensions to @nestjs/graphql deep imports

### PR DESCRIPTION
**Pull request by kaufmo**
## Problem

After upgrading `@nestjs/graphql` to 13.3.0, any project using `@comet/cms-api` fails to start (and tests fail to load) with:

```
Error: Cannot find module '/.../node_modules/@nestjs/graphql/dist/plugin/plugin-constants'
    at finalizeEsmResolution (node:internal/modules/cjs/loader)
    at resolveExports (node:internal/modules/cjs/loader)
  code: 'MODULE_NOT_FOUND',
  path: '/.../node_modules/@nestjs/graphql'
```

## Cause

`@nestjs/graphql` 13.3.0 tightened its `package.json` `exports` map. The subpath pattern `"./*": "./*"` no longer falls back to a `.js` extension, so extensionless deep imports go through `finalizeEsmResolution` and fail.

`packages/api/cms-api/src/common/helper/partial-type.helper.ts` does three such extensionless deep imports:

- `@nestjs/graphql/dist/plugin/plugin-constants`
- `@nestjs/graphql/dist/schema-builder/utils/get-fields-and-decorator.util`
- `@nestjs/graphql/dist/type-helpers/type-helpers.utils`

Verified with plain Node:

```
node -e "require('@nestjs/graphql/dist/plugin/metadata-loader')"     -> MODULE_NOT_FOUND
node -e "require('@nestjs/graphql/dist/plugin/metadata-loader.js')"  -> OK
```

## Fix

Append `.js` to each of those three deep imports. Resolves correctly under both 13.2.x and 13.3.x.

## Changeset

Patch bump for `@comet/cms-api`.

### CODE REVIEW

File: packages/api/cms-api/src/common/helper/partial-type.helper.ts [hunk 1]
```diff
@@ -3,9 +3,9 @@ import type { Type } from "@nestjs/common";
 import { isFunction } from "@nestjs/common/utils/shared.utils";
 import { Field } from "@nestjs/graphql";
 import type { ClassDecoratorFactory } from "@nestjs/graphql/dist/interfaces/class-decorator-factory.interface";
-import { METADATA_FACTORY_NAME } from "@nestjs/graphql/dist/plugin/plugin-constants";
-import { getFieldsAndDecoratorForType } from "@nestjs/graphql/dist/schema-builder/utils/get-fields-and-decorator.util";
-import { applyFieldDecorators } from "@nestjs/graphql/dist/type-helpers/type-helpers.utils";
+import { METADATA_FACTORY_NAME } from "@nestjs/graphql/dist/plugin/plugin-constants.js";
+import { getFieldsAndDecoratorForType } from "@nestjs/graphql/dist/schema-builder/utils/get-fields-and-decorator.util.js";
+import { applyFieldDecorators } from "@nestjs/graphql/dist/type-helpers/type-helpers.utils.js";
```
[the remark this answers is not in the document]
Comment (kaufmo) [reply packages/api/cms-api/src/common/helper/partial-type.helper.ts:8]: @copilot apply changes based on [this feedback](https://github.com/vivid-planet/comet/pull/5526#discussion_r3143404296)

[the remark this answers is not in the document]
Comment (kaufmo) [reply packages/api/cms-api/src/common/helper/partial-type.helper.ts:8]: @copilot apply changes based on [this feedback](https://github.com/vivid-planet/comet/pull/5526#discussion_r3143404296)

File: .changeset/fix-cms-api-graphql-13-3-imports.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"@comet/cms-api": patch
+---
+
+Fix `MODULE_NOT_FOUND` errors caused by extensionless deep imports of `@nestjs/graphql` internals in `PartialType`. `@nestjs/graphql` 13.3.0 tightened its `exports` map so that the `"./*": "./*"` pattern no longer maps to `.js` automatically. The deep imports of `plugin-constants`, `get-fields-and-decorator.util` and `type-helpers.utils` now use explicit `.js` extensions.
```
[the remark this answers is not in the document]
Comment (kaufmo) [reply .changeset/fix-cms-api-graphql-13-3-imports.md]: @copilot apply changes based on [this feedback](https://github.com/vivid-planet/comet/pull/5526#discussion_r3143404307)

**Comment by kaufmo** [comment]
@copilot also fix lint errors see action run

**Review by nsams — APPROVED** [review]
